[package]
name = "hyper-rustls"
version = "0.1.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls+hyper integration for pure rust HTTPS"
homepage = "https://github.com/ctz/hyper-rustls"
repository = "https://github.com/ctz/hyper-rustls"

[dependencies]
futures = "0.1.13"
rustls = "0.8"
tokio-core = "0.1.7"
tokio-io = "0.1.1"
tokio-proto = "0.1"
tokio-rustls = { version = "0.2", features = [ "tokio-proto" ] }
tokio-service = "0.1.0"
webpki-roots = "0.10.0"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
default-features = false
